Update CloudEvents
cncf/landscape pull request #2936
Opened 2022-12-22 17:11 UTC by duglin

Signed-off-by: Doug Davis <dug@microsoft.com>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you added your SVG to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~30 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

2022-12-22 17:13 UTC, duglin commented
I can't view the logs from netlify to see what's wrong

2022-12-22 21:45 UTC, onlydole requested changes
Thank you for this PR, @duglin - I left some minor comments for updating the dates to a valid format for the landscape YAML.

2022-12-22 21:45 UTC, onlydole commented on landscape.yml
> +              summary_release_rate: 2019/10/24
```suggestion
              summary_release_rate: 2019-10-24
```

2022-12-22 21:45 UTC, onlydole commented on landscape.yml
> +            joined: 2018/05/15
```suggestion
            joined: 2018-05-15
```

2022-12-22 21:53 UTC, duglin commented on landscape.yml
> +              summary_release_rate: 2019/10/24
done

2022-12-22 21:53 UTC, duglin commented on landscape.yml
> +            joined: 2018/05/15
done

2022-12-22 21:53 UTC, duglin commented
@onlydole made the suggested edits. Any idea why netlify isn't happy?

2022-12-22 22:05 UTC, onlydole commented
Looks like Netlify has an error and no logs are showing for me. 

@AndreyKozlov1984 - do you see what the error is?

2022-12-23 13:18 UTC, duglin commented
LGTM

2022-12-23 14:43 UTC, merged