Add 🐙 userver
cncf/landscape pull request #3540
Opened 2023-10-04 12:53 UTC by apolukhin

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ ] Have you added your SVG to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~30 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

2023-10-04 15:25 UTC, apolukhin commented
LGTM

2023-10-11 07:22 UTC, apolukhin commented
Hi,

@jeefy do I have to change something? I see no emoji usage in other projects. Are they forbidden?

2023-10-18 15:45 UTC, castrojo commented
I'm ready to merge this but if we add emojis then we have to start caring about how it looks on the front end design wise, etc. 

If you wouldn't mind adjusting for plain text then this is ready to go, thanks!

(It is quite cute though!)

2023-10-18 15:48 UTC, castrojo requested changes

2023-10-18 15:48 UTC, castrojo commented on landscape.yml
> +                🐙 userver solves the problem of efficient
```suggestion
                userver solves the problem of efficient
```

2023-10-19 16:17 UTC, apolukhin commented
LGTM

2023-10-20 13:33 UTC, castrojo approved these changes

2023-10-20 13:34 UTC, merged