Add secureCodeBox project to landscape
cncf/landscape pull request #3565
Opened 2023-10-17 14:20 UTC by Weltraumschaf

2023-10-18 10:16 UTC, Weltraumschaf commented
Hi there 👋

I guess, the Netlify errors in the pipeline are because my fork has no rights to do things on your Netlify, right?

2023-10-18 15:35 UTC, castrojo requested changes

2023-10-18 15:37 UTC, castrojo commented
Yeah looks like they timed out, let's get past the first yml check and then I'll dig into the netlify logs. Thanks!

2023-10-19 07:36 UTC, Weltraumschaf commented on landscape.yml
> +            homepage_url: httpw://www.securecodebox.io/
Fixed.

2023-10-20 14:18 UTC, Weltraumschaf commented
@castrojo is this caused by my changes? 🤔

> [406] [http://www.amplifypartners.com/](http://www.amplifypartners.com/) | Failed: Network error: Not Acceptable

2023-10-20 18:46 UTC, Weltraumschaf commented
We don't have Crunchbase (didn't knew it until now). I simply omitted the key `crunchbase` in the YAML. Is this wrong?

2023-10-23 08:25 UTC, Weltraumschaf commented
Ok, I learned that there is a crunchbase URL to our organisation. No idea where this came from and for what it is good for, but I added it.

2023-10-23 13:14 UTC, castrojo approved these changes

2023-10-23 13:16 UTC, merged