Adding kube-burner to cncf landscape
cncf/landscape pull request #3671
Opened 2024-01-04 00:17 UTC by rsevilla87

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ ] Have you added your SVG to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~30 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

2024-01-04 00:55 UTC, rsevilla87 commented
LGTM

2024-01-12 16:02 UTC, castrojo requested changes

2024-01-12 16:02 UTC, castrojo commented on landscape.yml
> +              accepted: '2023-18-12'
```suggestion
              accepted: '2023-12-18'
```

2024-01-12 16:02 UTC, castrojo commented on landscape.yml
> +              accepted: '2023-18-12'
I think this is what you mean. 😄

2024-01-12 18:19 UTC, rsevilla87 commented
Moving this one to draft until we get an answer from https://github.com/kubernetes/community/pull/7678

2024-01-18 14:56 UTC, castrojo approved these changes

2024-01-18 14:57 UTC, merged