Adding Numaflow to Streaming & Messaging
cncf/landscape pull request #3739
Opened 2024-02-07 21:33 UTC by syayi

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ ] Have you added your SVG to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other [guidelines](https://github.com/cncf/landscape#new-entries)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?

2024-02-08 14:43 UTC, castrojo requested changes

2024-02-08 14:43 UTC, castrojo commented on landscape.yml
> +            logo: numaproj-logo.svg
```suggestion
          - item:
            name: Numaflow
            description: K8s native real-time data and stream processing engine
            homepage_url: https://numaflow.numaproj.io/
            repo_url: https://github.com/numaproj/numaflow
            logo: numaproj-logo.svg
```

2024-02-08 14:43 UTC, castrojo commented on landscape.yml
> +            logo: numaproj-logo.svg
You'll need at least a homepage_url

2024-02-08 16:40 UTC, syayi commented
@castrojo thanks for the review. Added the requested changes

2024-02-09 00:01 UTC, carasen12 approved these changes

2024-02-09 00:18 UTC, castrojo commented
Alright all set, thanks!

2024-02-09 00:18 UTC, castrojo approved these changes

2024-02-09 00:19 UTC, merged