adding CNAI group
cncf/landscape pull request #3866
Opened 2024-05-10 15:37 UTC by ronaldpetty

This is second PR, following https://github.com/cncf/landscape2-sites/pull/85 (notice different repo).

2024-05-10 15:40 UTC, tegioz commented
Please note that until we merge https://github.com/cncf/landscape2-sites/pull/85 the preview won't be complete (as it'll be using the current settings, where the new group doesn't exist yet) 🙂

2024-05-10 15:51 UTC, tegioz commented
Settings update merged and preview ready! All yours @caniszczyk 🙂

<img width="1682" alt="cnai" src="https://github.com/cncf/landscape/assets/1213902/00ea64dd-4d30-4777-ae1e-cebdec7c208b">

2024-05-10 16:01 UTC, cynthia-sg requested changes

2024-05-10 17:37 UTC, cynthia-sg approved these changes

2024-05-12 23:48 UTC, caniszczyk commented
Thanks @ronaldpetty and all

2024-05-12 23:48 UTC, merged