Propose adding a new subcat to the GNAI group and adding Chainguard Images to it
cncf/landscape pull request #3878
Opened 2024-05-15 13:03 UTC by MordodeMaru

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you added your SVG to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other [guidelines](https://github.com/cncf/landscape#new-entries)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?

2024-05-15 14:39 UTC, tegioz commented
@castrojo please note that the error you see in the preview is due to an error introduced by the changes suggested by this PR. So this often will be an alert that something is wrong and needs to be fixed 🙂 This is something the validate check will report as well as soon as it's approved (maybe we could consider authorizing this check to run without approval so that users can be made aware of the errors and fix them).

<img width="819" alt="Screenshot 2024-05-15 at 16 37 30" src="https://github.com/cncf/landscape/assets/1213902/08d38327-8abb-45d4-b143-48394b9cdd6d">

<br/>

<img width="931" alt="Screenshot 2024-05-15 at 16 33 23" src="https://github.com/cncf/landscape/assets/1213902/57df6bca-c461-408e-ab8a-8c95e6fb1a27">

2024-05-15 15:15 UTC, MordodeMaru reviewed
I think I have amended the error in line 18395

2024-05-15 15:21 UTC, cynthia-sg requested changes

2024-05-16 14:00 UTC, MordodeMaru commented on landscape.yml
> +      name: Hardened Container Images
Sure. How do I request a new subcategory?

2024-05-16 14:00 UTC, MordodeMaru commented on landscape.yml
> +            clomonitor_name: Chainguard Images
Indeed

2024-05-16 14:00 UTC, MordodeMaru commented on landscape.yml
> +                url: https://www.chainguard.dev/unchained/chainguards-trail-of-bits-security-assessment
Ok.

2024-05-16 14:43 UTC, cynthia-sg commented on landscape.yml
> +          allow_duplicate_repo: true
Delete the line, please.

2024-05-16 14:46 UTC, MordodeMaru commented on landscape.yml
> +            slack_url: https://slack.kubernetes.io/
The community meets in the #apko channel of that Slack community.

2024-05-16 14:47 UTC, MordodeMaru commented on landscape.yml
> +      name: Hardened Container Images
I don't think we will add Chainguard Images if it's not to the right category. We need to solve that first.

2024-05-16 14:53 UTC, cynthia-sg commented on landscape.yml
> +      name: Hardened Container Images
You could bring it up in the landscapers channel in Slack, maybe in this [thread](https://cloud-native.slack.com/archives/CM09QERF1/p1714450672828699) where the CNAI landscape group has been discussed recently.

2024-05-16 14:54 UTC, MordodeMaru commented on landscape.yml
> +      name: Hardened Container Images
I will. Thanks!

2024-05-16 14:55 UTC, cynthia-sg commented on landscape.yml
> +            slack_url: https://slack.kubernetes.io/
Ok, you can use `[chat_channel](chat_channel)` field

2024-05-16 14:55 UTC, MordodeMaru commented
Closing this PR until I get some clarity on category creation.

2024-05-16 14:57 UTC, closed without merging

2024-05-16 14:57 UTC, MordodeMaru commented
Closing this PR until I get some clarity on category creation.