Update some logos that are pulled in to CNCF.io
cncf/landscape pull request #3913
Opened 2024-06-11 10:24 UTC by thetwopct

We pull in the logos from Landscape on to the CNCF.io home page. This fixes a few issues with some of them - large image sizes, wrong images used, wrong colors. The images submitted were taken from https://github.com/cncf/artwork. 

There was also an issue when I downloaded the repo for file "hami.svg" due to a colliding git path, which I have fixed in this PR. 

```
warning: the following paths have collided (e.g. case-sensitive paths on a case-insensitive filesystem) and only one from the same colliding group is in the working tree:

  'hosted_logos/HAMi.svg'
  'hosted_logos/hami.svg'
```

Commits:

- Fix case conflict and use one file name for hami.svg
- Updating Keycloak logo to stacked version
- Updating OpenKruise logo to color variant
- Updating Volcano project logo, reduced size from 176KB to 9KB

2024-06-11 10:53 UTC, cynthia-sg requested changes

2024-06-11 10:53 UTC, cynthia-sg commented on hosted_logos/HAMi.svg
Could you please also use `./hami.svg` in [this entry](https://github.com/cncf/landscape/blob/5b9f010e9fb1257eabc8cbe78e8260b8bd981582/landscape.yml#L18486)?

<img width="960" alt="Screenshot 2024-06-11 at 12 48 11" src="https://github.com/cncf/landscape/assets/1440981/c1011bdb-3d2f-4fb3-a7eb-ba5d485f3a2d">

2024-06-11 11:02 UTC, thetwopct commented on hosted_logos/HAMi.svg
Done. Note to self: just leave it next time ;)

2024-06-11 11:15 UTC, cynthia-sg commented on hosted_logos/HAMi.svg
I think the change was worth it, even if it required a minor update in the `landscape.yml` file

2024-06-11 11:15 UTC, cynthia-sg approved these changes

2024-06-12 13:11 UTC, cjyabraham approved these changes

2024-06-12 13:12 UTC, merged