Update Trivy
cncf/landscape pull request #4112
Opened 2024-11-03 12:41 UTC by itaysk

was asked to create an new PR instead of https://github.com/cncf/landscape/pull/3898

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ ] Have you added your SVG to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other [guidelines](https://github.com/cncf/landscape#new-entries)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?

2024-11-06 14:03 UTC, castrojo requested changes

2024-11-06 14:03 UTC, castrojo commented on landscape.yml
> +           - item:
```suggestion
          - item:
```

2024-11-06 14:07 UTC, itaysk commented on landscape.yml
> +           - item:
thanks

2024-11-08 19:42 UTC, itaysk commented
@castrojo I think this is ready? BTW, I'm not sure why trivy-operator was added separately from trivy (it wasn't us who added it). I wouldn't mind removing trivy-operator altogether since IMO it's a module of Trivy

2024-11-09 16:19 UTC, caniszczyk commented
@itaysk if you want to remove the operator please send an updated PR, happy to if this basically is the same as your PR here

2024-11-09 18:06 UTC, castrojo approved these changes

2024-11-09 18:12 UTC, itaysk commented
@caniszczyk should I wait for this to be merged and then send another PR or should I just remove it within this PR?

2024-11-10 01:03 UTC, castrojo commented
@itaysk I'll merge this now, send one to remove it and tag me in it and i'll merge it asap, thanks!

2024-11-10 01:03 UTC, merged

2024-11-10 09:01 UTC, itaysk commented
thanks @castrojo , I've created https://github.com/cncf/landscape/pull/4126

P.S I said earlier that we (Trivy) didn't add it but I checked and indeed it was added by our team member. Still, I don't see a special reason to have a separate entry for it.